#include "protheus.ch"
#include "parmtype.ch"

#define __IS_THE_ADDONS_EXECUTION_ENABLED__ .T.

procedure U_HBBridgeConnectionTest(cHost, nPort, nTimeout)

    local jParams:=JSONObject():New() as json

    local jResponse as json

    local lOk:=.T. as logical

    local oClient as object

    paramtype 1 var cHost as character default "127.0.0.1"
    paramtype 2 var nPort as numeric default 1512
    paramtype 3 var nTimeout as numeric default 5000

    jParams["source"]:="protheus"
    jParams["company"]:="T1"
    jParams["user"]:="rpc-test"
    jParams["message"]:="Primeira integracao RPC"
    jParams["largePayload"]:=Replicate("X", 200000)

    oClient:=hbBridge.client.THBBridgeClient():New(cHost,nPort,nTimeout)
    jResponse:=oClient:CallService("Health", jParams)

    if ((!jResponse:HasProperty("success")).or.(!jResponse["success"]))
        ConOut("hbBridge Health falhou: "+jResponse:ToJSON())
        lOk:=.F.
    else
        ConOut("hbBridge Health Protheus OK: "+jResponse:ToJSON())
    endif
    FreeObj(@jResponse)

    if (__IS_THE_ADDONS_EXECUTION_ENABLED__)
        jResponse:=oClient:CallService("ADDON.examples\sample_addon.prg", jParams)
        if ((!jResponse:HasProperty("success")).or.(!jResponse["success"]))
            ConOut("hbBridge ADDON. falhou: "+jResponse:ToJSON())
            lOk:=.F.
        else
            ConOut("hbBridge ADDON. Protheus OK: "+jResponse:ToJSON())
        endif
        FreeObj(@jResponse)
    endif

    jResponse:=oClient:CallService("Echo", jParams)

    FreeObj(@oClient)

    if ((!jResponse:HasProperty("success")).or.(!jResponse["success"]))
        ConOut("hbBridge Echo falhou: "+jResponse:ToJSON())
        lOk:=.F.
    elseif (;
                    (!jResponse:HasProperty("params"));
                .or.(jResponse["params"]["message"]!=jParams["message"]);
                .or.(Len(jResponse["params"]["largePayload"])!=200000);
   )
        ConOut("hbBridge Echo nao devolveu os dados enviados: "+jResponse:ToJSON())
        lOk:=.F.
    endif

    if (lOk)
        ConOut("hbBridge RPC Protheus OK: "+jResponse:ToJSON())
    endif

    FreeObj(@jParams)
    FreeObj(@jResponse)

return
